package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.31

import (
	"context"
	"fmt"
	"github.com/go-nova/cmd/demo/internal/dao/model"

	"github.com/go-nova/cmd/demo/internal/graphql/generated"
)

// User is the resolver for the User field.
func (r *mutationResolver) User(ctx context.Context) (*model.UserMutationObject, error) {
	panic(fmt.Errorf("not implemented: User - User"))
}

// User is the resolver for the User field.
func (r *queryResolver) User(ctx context.Context) (*model.UserQueryObject, error) {
	panic(fmt.Errorf("not implemented: User - User"))
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
