name: "Tom"
preferences:
  favouriteColour: "red"
colours:
  - "red"
  - "green"
  - "blue"
colourCodes:
  - name: "red"
    rgb: "ff0000"
    tag: 0
  - name: "green"
    rgb: "00ff00"
    tag: 1
  - name: "blue"
    rgb: "0000ff"
    tag: 2